export enum NotificationType {
  FRIEND_REQUEST = "FRIEND_REQUEST",
  FRIEND_ACCEPTED = "FRIEND_ACCEPTED",
  ROOM_INVITE = "ROOM_INVITE",
  ROOM_JOINED = "ROOM_JOINED",
  GAME_STARTED = "GAME_STARTED",
  GAME_FINISHED = "GAME_FINISHED",
  ACHIEVEMENT = "ACHIEVEMENT",
  SYSTEM = "SYSTEM",
  ADMIN = "ADMIN",
}
